const NotesActionTypes = {
  ADD_NEW_NOTE_START: "ADD_NEW_NOTE_START",
  ADD_NEW_NOTE_SUCCESS: "ADD_NEW_NOTE_SUCCESS",
  ADD_NEW_NOTE_FAILURE: "ADD_NEW_NOTE_FAILURE",
  FETCH_ALL_NOTES_START: "FETCH_ALL_NOTES_START",
  FETCH_ALL_NOTES_SUCCESS: "FETCH_ALL_NOTES_SUCCESS",
  FETCH_ALL_NOTES_FAILURE: "FETCH_ALL_NOTES_FAILURE",
};

export default NotesActionTypes;
