const NotesActionTypes = {
  FETCH_RECENT_NOTES_START: "FETCH_RECENT_NOTES_START",
  FETCH_RECENT_NOTES_SUCCESS: "FETCH_RECENT_NOTES_SUCCESS",
  FETCH_RECENT_NOTES_FAILURE: "FETCH_RECENT_NOTES_FAILURE",
  FETCH_CATEGORY_NOTES_START: "FETCH_CATEGORY_NOTES_START",
  FETCH_CATEGORY_NOTES_SUCCESS: "FETCH_CATEGORY_NOTES_SUCCESS",
  FETCH_CATEGORY_NOTES_FAILURE: "FETCH_CATEGORY_NOTES_FAILURE",
};

export default NotesActionTypes;
