const NotesActionTypes = {
  SAVE_NOTE_START: "SAVE_NOTE_START",
  SAVE_NOTE_SUCCESS: "SAVE_NOTE_SUCCESS",
  SAVE_NOTE_FAILURE: "SAVE_NOTE_FAILURE",
  FETCH_ALL_NOTES_START: "FETCH_ALL_NOTES_START",
  FETCH_ALL_NOTES_SUCCESS: "FETCH_ALL_NOTES_SUCCESS",
  FETCH_ALL_NOTES_FAILURE: "FETCH_ALL_NOTES_FAILURE",
};

export default NotesActionTypes;
